### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [6]:
np.random.rand(3,10)

array([[0.19039028, 0.96330224, 0.63273767, 0.35771672, 0.39727925,
        0.21036789, 0.3259498 , 0.79000077, 0.53154382, 0.6772862 ],
       [0.50204932, 0.49372089, 0.24435998, 0.00790419, 0.18373865,
        0.63464723, 0.56829734, 0.31613241, 0.28516431, 0.8926963 ],
       [0.95460383, 0.46289615, 0.61089185, 0.89340895, 0.60528524,
        0.66221029, 0.19162397, 0.17064498, 0.42828971, 0.17574962]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [9]:
np.random.randn(3,4,2)

array([[[ 0.6681303 , -2.4110233 ],
        [ 0.70218226, -0.9214862 ],
        [-0.4881914 , -0.36860581],
        [-1.55601029, -0.48548134]],

       [[ 0.85871065, -0.01969938],
        [-0.70871265,  0.66524821],
        [-0.86103548,  0.51004761],
        [ 2.02591799, -0.13124794]],

       [[-0.78835142, -1.16430354],
        [ 0.03115864, -1.57792027],
        [-0.06138213,  0.28413211],
        [ 0.69650597, -1.41885072]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [11]:
np.random.randint(1,100,size=(3,5))

array([[58, 90,  5, 64, 58],
       [77, 21,  9, 75, 85],
       [94, 20, 90,  1, 12]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [25]:
np.random.seed(100)

In [51]:
np.random.seed(100)
np.random.randn(3,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [53]:
np.random.choice(100, (3, 4))

array([[71, 80,  2, 94],
       [19, 98, 63, 53],
       [27, 56, 30, 48]])

In [59]:
x=np.array([1,3,4,5,6,7,8.3,])
np.random.choice(x,size=(2,3),replace=False)

array([[5. , 7. , 1. ],
       [8.3, 6. , 3. ]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [60]:
np.random.uniform(1.0,3.0,size=(4,5))

array([[1.14973376, 2.65018972, 2.67226363, 1.15078982, 1.02280158],
       [1.09684114, 1.71424542, 2.33138675, 1.02277922, 1.21583553],
       [2.8020262 , 2.58975752, 2.62292196, 2.28055611, 2.24955902],
       [1.29101502, 2.1404318 , 1.130225  , 1.62682514, 1.43413153]])

In [62]:
np.random.normal(size=(3,4))

array([[-2.55944758,  0.94631055,  0.79067165,  0.68000189],
       [ 0.71660582,  0.47770485, -0.66623993,  0.08448008],
       [-0.33876049,  0.70592118, -1.6017614 ,  0.39324807]])